; generated by genTables.js

TSTEP           equ     196
PBASE           equ     -13107
KA              equ     419
KB              equ     4577446
Z1_MIN          equ     520
Z1_MAX          equ     2613
