"use strict";

// Generates constants for main.asm. The per-state tables are built at runtime
// from these, so the checks here repeat the same integer maths.

const CFG = {
  // changes how aggressively the eight frequency states spread out
  pBase: -.8,
  // pBase: -0.6,

  // control the two spatial scales.
  aDiv: 210*2,
  bDiv: 105*1.5,
  // aDiv: 210,
  // bDiv: 105,

  // How much original "t" elapses across the 320-pixel image.
  // changes how much the scene evolves horizontally.
  timeSweepRadians: 6.0,

  // Screen dimensions
  width: 320,
  height: 256,

  // Original Dwitter vertical coordinate space.
  sourceHeight: 1080,

  // Phase representation:
  // 256-entry waveform, phase stored as Q8 table position.
  lutSize: 256,
  phaseFracBits: 8,
};

const TAU = Math.PI * 2;

const phaseScale = CFG.lutSize / TAU;

const qPhase = 1 << CFG.phaseFracBits;

const sourcePerOutputY = CFG.sourceHeight / CFG.height;

const timePerX = CFG.timeSweepRadians / CFG.width;

// ============================================================
// Constants
//
// For p = pBase^state:
//
//   A = p*KA   cos(t + i/210*p): one output Y step in Q8 LUT phase
//   B = KB/p   cos(i/(105*p))
//   C = T/p    cos(t/p): increment per output X column
//
// p is Q14 at runtime.
// ============================================================

const PBASE = Math.round(CFG.pBase * (1 << 14));

// A = (p*KA)>>16, so KA is Q2
const KA = Math.round((sourcePerOutputY / CFG.aDiv) * phaseScale * qPhase * 4);

// B = KB/p, so KB is Q14
const KB = Math.round(
  (sourcePerOutputY / CFG.bDiv) * phaseScale * qPhase * (1 << 14),
);

// Main t phase increment.
const T = Math.round(timePerX * phaseScale * qPhase);

// ============================================================
// z1 range, repeating the table setup in main.asm
// ============================================================

// Generated waveform, as built at startup
function sinTab() {
  const tab = new Array(256).fill(0);

  let d1 = 0;
  let d2 = 127;
  let i = 0;

  do {
    d2 -= 2;
    tab[i] = d1;
    tab[i + 127] -= d1;
    i++;
    d1 += d2;
  } while (d1 !== 0);

  return tab;
}

const SIN = sinTab();

let z1Min = Infinity;
let z1Max = -Infinity;

let p = 1 << 14;

for (let state = 0; state < 8; state++) {
  // z1 = (state+3)*256 - ((p*sin)>>18)
  for (const s of SIN) {
    const z1 = (state + 3) * 256 - Math.floor((p * s) / (1 << 18));

    z1Min = Math.min(z1Min, z1);
    z1Max = Math.max(z1Max, z1);
  }

  // B and C must fit in a word
  for (const v of [KB / p, (T << 14) / p]) {
    if (Math.abs(v) >= 32768) {
      throw new Error(`step out of range for state ${state}: ${v}`);
    }
  }

  p = Math.floor((p * PBASE) / (1 << 14));
}

// MainLoop assumes z1 is always in 1..$fff: z1 and z stay positive (runs
// only go down) and runs are at most 7 pixels.
if (z1Min <= 0 || z1Max >= 0x1000) {
  throw new Error(`z1 out of range: ${z1Min}..${z1Max}`);
}

// ============================================================
// Assembler output
// ============================================================

console.log("; generated by genTables.js\n");

console.log(`TSTEP           equ     ${T}`);
console.log(`PBASE           equ     ${PBASE}`);
console.log(`KA              equ     ${KA}`);
console.log(`KB              equ     ${KB}`);
console.log(`Z1_MIN          equ     ${z1Min}`);
console.log(`Z1_MAX          equ     ${z1Max}`);
